#!/bin/bash
start() {
  echo -n "Starting $prog: "
  WILDFLY_PIDFILE=`ps -ef | grep "wildfly-10.1.0.Final/standalone" | grep -v grep  | awk '{print$2}'`
  if [[ ! -z $WILDFLY_PIDFILE ]]; then
    echo -n "$WILDFLY_PIDFILE is already running"
    echo
    return 0
  else
   nohup /home/lms/wildfly-10.1.0.Final/bin/standalone.sh -b 0.0.0.0 > /dev/null 2>&1 &
  fi
sleep 8
    echo
    return 0
}

stop() {
  count=0
  WILDFLY_PIDFILE=`ps -ef | grep "wildfly-10.1.0.Final/modules" | grep -v grep  | awk '{print$2}' | head -1`
  echo -n $"Stopping: $WILDFLY_PIDFILE: "
  if [ $WILDFLY_PIDFILE ]; then
    kpid=$WILDFLY_PIDFILE
    kill -15 $kpid
   sleep 5

if  [ $WILDFLY_PIDFILE ]; then
         kpid=$WILDFLY_PIDFILE
         kill -9 $kpid
      fi


  fi
  echo
}
########################################################################################################
status () {
WILDFLY_PIDFILE=`ps -ef | grep "wildfly-10.1.0.Final/standalone" | grep -v grep  | awk '{print$2}'`
  if [[ ! -z $WILDFLY_PIDFILE ]]; then
    echo -n "$WILDFLY_PIDFILE wildfly10 is running"
    echo
    return 0
  else
   echo -n "$WILDFLY_PIDFILE wildfly10 is stoped"
   sleep 0
  fi
}
#######################################################################################################
case "$1" in
  start)
      start
      ;;
  stop)
      stop
      ;;
  status)
      status
      ;;
  restart)
      $0 stop
      $0 start
      ;;
  *)
      ## If no parameters are given, print which are avaiable.
      echo "Usage: $0 {start|stop|status|restart}"
      exit 1
      ;;
esac

